from VOTPUSK_SDET.VOTPUSK.Hotel_main.hotels_second_page.hotel_filters.hotel_filters import FiltersLocators
from VOTPUSK_SDET.VOTPUSK.Hotel_main.hotels_second_page.tests.TestBase import BaseTest
from VOTPUSK_SDET.VOTPUSK.Hotel_main.hotels_second_page.second_page_form.second_page_form import SecondFormLocators
from VOTPUSK_SDET.VOTPUSK.Hotel_main.hotels_second_page.config.configuration import TestDataSecondPage


class TestSecondHotelPage(BaseTest):
    def test_hotel_booking_form(self, driver):
        driver.get(TestDataSecondPage.URL)
        check_the_form_visibility = SecondFormLocators(driver)
        check_the_form_visibility.check_the_form_visibility()
        clear_default_value_and_assert_the_len = SecondFormLocators(driver)
        clear_default_value_and_assert_the_len.clear_default_value_and_assert_the_len()
        select_check_in = SecondFormLocators(driver)
        select_check_in.select_check_in()
        select_check_out = SecondFormLocators(driver)
        select_check_out.select_check_out()
        select_dropdown_quantity = SecondFormLocators(driver)
        select_dropdown_quantity.select_dropdown_quantity()
        check_input_sign = SecondFormLocators(driver)
        check_input_sign.check_input_sign()
        randint_click = SecondFormLocators(driver)
        randint_click.randint_click()
        check_dropdown_quantity_kids = SecondFormLocators(driver)
        check_dropdown_quantity_kids.check_dropdown_quantity_kids()
        click_to_dropdown_kids = SecondFormLocators(driver)
        click_to_dropdown_kids.click_to_dropdown_kids()
        check_visibility_dropdown_len = SecondFormLocators(driver)
        check_visibility_dropdown_len.check_visibility_dropdown_len()
        assert_clickable_search_button = SecondFormLocators(driver)
        assert_clickable_search_button.assert_clickable_search_button()

    def test_hotel_filters(self, driver):
        driver.get(TestDataSecondPage.URL)
        check_visibility_range_block = FiltersLocators(driver)
        check_visibility_range_block.check_visibility_range_block()
        assert_short_details_on_block = FiltersLocators(driver)
        assert_short_details_on_block.assert_short_details_on_block()
        scroll_to_average_price_slider = FiltersLocators(driver)
        scroll_to_average_price_slider.scroll_to_average_price_slider(100, 0)
        check_hidden_arrow = FiltersLocators(driver)
        check_hidden_arrow.check_hidden_arrow()
        assert_cost_block = FiltersLocators(driver)
        assert_cost_block.assert_cost_block()
        clear_and_check_functionality_field_form_from = FiltersLocators(driver)
        clear_and_check_functionality_field_form_from.clear_and_check_functionality_field_form_from()
        clear_and_check_functionality_field_form_to = FiltersLocators(driver)
        clear_and_check_functionality_field_form_to.clear_and_check_functionality_field_form_to()

    def test_star_rating_filter(self, driver):
        driver.get(TestDataSecondPage.URL)
        check_the_visibility_and_clickable_hidden_arrow = FiltersLocators(driver)
        check_the_visibility_and_clickable_hidden_arrow.check_the_visibility_and_clickable_hidden_arrow()
        scroll_to_widget = FiltersLocators(driver)
        scroll_to_widget.scroll_to_widget()
        check_star_rating_container_hotel_present = FiltersLocators(driver)
        check_star_rating_container_hotel_present.check_star_rating_container_hotel_present()
        check_data_name_p = FiltersLocators(driver)
        check_data_name_p.check_data_name_p()
        check_the_check_box_rating = FiltersLocators(driver)
        check_the_check_box_rating.check_the_check_box_rating()

    def test_rating_hotel(self, driver):
        driver.get(TestDataSecondPage.URL)
        scroll_to_rating_hotel = FiltersLocators(driver)
        scroll_to_rating_hotel.scroll_to_rating_hotel()
        check_hotel_rating_container = FiltersLocators(driver)
        check_hotel_rating_container.check_hotel_rating_container()
        check_rating_blocks = FiltersLocators(driver)
        check_rating_blocks.check_rating_blocks()
        check_each_rating_blocks = FiltersLocators(driver)
        check_each_rating_blocks.check_each_rating_blocks()
        check_visibility_hidden_arrow = FiltersLocators(driver)
        check_visibility_hidden_arrow.check_visibility_hidden_arrow()

    def test_distance_to_the_center_filter(self, driver):
        driver.get(TestDataSecondPage.URL)
        scroll_to_distance_filter = FiltersLocators(driver)
        scroll_to_distance_filter.scroll_to_distance_filter()
        wait_page_load = FiltersLocators(driver)
        wait_page_load.wait_page_load()
        check_the_h3 = FiltersLocators(driver)
        check_the_h3.check_the_h3()
        check_hidden_upper_arrow = FiltersLocators(driver)
        check_hidden_upper_arrow.check_hidden_upper_arrow()
        scroll_range_slider = FiltersLocators(driver)
        scroll_range_slider.scroll_range_slider(-50, 0)

    def test_type_of_apartments(self, driver):
        driver.get(TestDataSecondPage.URL)
        scroll_to_type_of_apartments = FiltersLocators(driver)
        scroll_to_type_of_apartments.scroll_to_type_of_apartments()
        page_load = FiltersLocators(driver)
        page_load.page_load()
        check_type_of_apartments_container = FiltersLocators(driver)
        check_type_of_apartments_container.check_type_of_apartments_container()
        check_the_h6_data_name = FiltersLocators(driver)
        check_the_h6_data_name.check_the_h6_data_name()
        assert_check_boxes = FiltersLocators(driver)
        assert_check_boxes.assert_check_boxes()
        check_hidden_arrow_type_of_apartments = FiltersLocators(driver)
        check_hidden_arrow_type_of_apartments.check_hidden_arrow_type_of_apartments()
        check_the_under_hidden_link = FiltersLocators(driver)
        check_the_under_hidden_link.check_the_under_hidden_link()

    def test_amenities_hotel(self, driver):
        driver.get(TestDataSecondPage.URL)
        scroll_to_amenities_hotel = FiltersLocators(driver)
        scroll_to_amenities_hotel.scroll_to_amenities_hotel()
        wait_page_load_element = FiltersLocators(driver)
        wait_page_load_element.wait_page_load_element()
        check_visibility_container_amenities_hotel = FiltersLocators(driver)
        check_visibility_container_amenities_hotel.check_visibility_container_amenities_hotel()
        check_h3_amenities_hotel = FiltersLocators(driver)
        check_h3_amenities_hotel.check_h3_amenities_hotel()
        check_amenities_check_bos_hotel = FiltersLocators(driver)
        check_amenities_check_bos_hotel.check_amenities_check_bos_hotel()
        check_amenities_hidden_link = FiltersLocators(driver)
        check_amenities_hidden_link.check_amenities_hidden_link()

    def test_amenities_room(self, driver):
        driver.get(TestDataSecondPage.URL)
        scroll_to_amenities_room = FiltersLocators(driver)
        scroll_to_amenities_room.scroll_to_amenities_room()
        check_amenities_in_the_room_container = FiltersLocators(driver)
        check_amenities_in_the_room_container.check_amenities_in_the_room_container()
        check_the_amenities_in_the_room_check_box = FiltersLocators(driver)
        check_the_amenities_in_the_room_check_box.check_the_amenities_in_the_room_check_box()
        check_the_upper_hidden_room_link = FiltersLocators(driver)
        check_the_upper_hidden_room_link.check_the_upper_hidden_room_link()
        check_the_upper_hidden_room_link = FiltersLocators(driver)
        check_the_upper_hidden_room_link.check_the_upper_hidden_room_link()